# Generated by Django 3.2.19 on 2023-06-09 16:34

import books.models
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Book ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=100, verbose_name="Book Title"
                    ),
                ),
                (
                    "title_ru",
                    models.CharField(
                        default="", max_length=100, verbose_name="Book Title in russian"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Book Description"),
                ),
                (
                    "description_source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Book Description Source",
                    ),
                ),
                ("date", models.DateField(verbose_name="Latest Release Date")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(
                            books.models._get_image_name, *("covers",), **{}
                        ),
                    ),
                ),
                (
                    "cover_image_source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Cover Image Source",
                    ),
                ),
                (
                    "promoted",
                    models.BooleanField(default=False, verbose_name="Promoted"),
                ),
                (
                    "duration_sec",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("HIDDEN", "Hidden")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "preview_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Preview URL",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=70,
                        verbose_name="Link Type Name",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Link Caption",
                    ),
                ),
                ("icon", models.ImageField(blank=True, null=True, upload_to="icons")),
                (
                    "disabled",
                    models.BooleanField(default=False, verbose_name="Disabled"),
                ),
                (
                    "url_regex",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="Url regex"
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("EVERYWHERE", "Everywhere"),
                            ("UNAVAILABLE_IN_BELARUS", "Unavailable In Belarus"),
                            ("USA_ONLY", "Usa Only"),
                        ],
                        max_length=50,
                        verbose_name="Availability",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Person Id",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=100, verbose_name="Person Name"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        default="",
                        max_length=100,
                        verbose_name="Person Name in russian",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Person Description"),
                ),
                (
                    "description_source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Person Description Source",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=functools.partial(
                            books.models._get_image_name, *("photos",), **{}
                        ),
                    ),
                ),
                (
                    "photo_source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Photo Source",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Person slug",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("PLURAL", "Plural"),
                        ],
                        max_length=20,
                        verbose_name="Person gender",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of birth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=50, verbose_name="Tag"),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        max_length=100,
                        verbose_name="Tag slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Tag Description"),
                ),
                ("hidden", models.BooleanField(default=False, verbose_name="Hidden")),
            ],
        ),
        migrations.CreateModel(
            name="Narration",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Narration ID",
                    ),
                ),
                (
                    "paid",
                    models.BooleanField(
                        default=False, verbose_name="Is narration paid?"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("BELARUSIAN", "Belarusian"), ("RUSSIAN", "Russian")],
                        max_length=20,
                        verbose_name="Language",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrations",
                        to="books.book",
                    ),
                ),
                (
                    "narrators",
                    models.ManyToManyField(
                        blank=True, related_name="narrations", to="books.Person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Link Id",
                    ),
                ),
                ("url", models.URLField(max_length=1024, verbose_name="URL")),
                (
                    "narration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="books.narration",
                    ),
                ),
                (
                    "url_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_type",
                        to="books.linktype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books_authored", to="books.Person"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.Tag"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="translators",
            field=models.ManyToManyField(
                blank=True, related_name="books_translated", to="books.Person"
            ),
        ),
    ]
