# Generated by Django 3.2.19 on 2023-06-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_fill_duration_narration_from_duration_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="duration_sec",
        ),
    ]
