# Generated by Django 3.2.19 on 2023-06-27 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_duration_sec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Publisher ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Publisher Name')),
                ('url', models.URLField(max_length=128, verbose_name='Publisher Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='icons')),
                ('description', models.TextField(blank=True, verbose_name='Publisher Description')),
            ],
        ),
        migrations.AddField(
            model_name='narration',
            name='publishers',
            field=models.ManyToManyField(related_name='narrations', to='books.Publisher'),
        ),
    ]
