# Generated by Django 3.2.19 on 2023-08-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_livelib_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='description',
            field=models.TextField(blank=True, verbose_name='Narration Description'),
        ),
    ]
