# Generated by Django 3.2.19 on 2023-10-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20231027_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='cover_image_source',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Cover Source'),
        ),
    ]
