# Generated by Django 3.2.19 on 2023-11-03 05:05

from django.db import migrations


def migrate_release_date(apps, schema_editor):
    """Copy release date from Book to Narrations."""
    Book = apps.get_model("books", "Book")
    for idx, book in enumerate(Book.objects.prefetch_related("narrations").all()):
        for narration in book.narrations.all():
            if narration.date is None:
                print(f"#{idx} Updating date {book.title}")
                narration.date = book.date
                narration.save()


def migrate_translators(apps, schema_editor):
    """Copy translators from Book to Narrations where Narrations don't have translation yet."""
    Book = apps.get_model("books", "Book")
    for idx, book in enumerate(Book.objects.prefetch_related("narrations").all()):
        if book.translators.count() == 0:
            continue
        has_translators = False
        for narration in book.narrations.all():
            if narration.translators.count() > 0:
                has_translators = True
        if has_translators:
            continue
        for narration in book.narrations.all():
            print(f"#{idx} Updating translators {book.title}")
            narration.translators.set(book.translators.all())
            narration.save()


def migrate_covers(apps, schema_editor):
    """Copy covers from Book to Narrations."""
    Book = apps.get_model("books", "Book")
    for idx, book in enumerate(Book.objects.prefetch_related("narrations").all()):
        if not bool(book.cover_image):
            continue
        for narration in book.narrations.all():
            if bool(narration.cover_image):
                print("Skipping " + narration.cover_image.url)
                continue
            print(f"#{idx} Updating covers {book.title}")
            narration.cover_image = book.cover_image
            narration.cover_image_source = book.cover_image_source
            narration.save()


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_narration_cover_image_source"),
    ]

    operations = [
        migrations.RunPython(migrate_release_date),
        migrations.RunPython(migrate_translators),
        migrations.RunPython(migrate_covers),
    ]
