# Generated by Django 3.2.19 on 2023-11-05 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20231103_0505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image_source',
        ),
    ]
