# Generated by Django 3.2.19 on 2023-11-16 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_remove_book_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="narration",
            name="date",
            field=models.DateField(
                default=datetime.date(2022, 1, 1), verbose_name="Release Date"
            ),
            preserve_default=False,
        ),
    ]
