# Generated by Django 5.0.1 on 2024-02-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_fill_preview_url_in_narration_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='preview_url',
        ),
    ]
