# Generated by Django 5.1.2 on 2024-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_remove_book_preview_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktype",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Адключана"),
        ),
    ]
