# Generated by Django 5.0.9 on 2024-10-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0021_alter_linktype_disabled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktype",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
    ]
