# Generated by Django 5.0.9 on 2025-12-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0022_alter_linktype_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="narration",
            name="title",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Narration Title"
            ),
        ),
    ]
