# Generated by Django 5.1.14 on 2026-01-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0023_narration_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linktype",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Адключана"),
        ),
    ]
