# Generated by Django 5.2.10 on 2026-01-31 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_linktype_disabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="ISBN",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ISBN Code",
                    ),
                ),
                (
                    "narration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="isbns",
                        to="books.narration",
                    ),
                ),
            ],
        ),
    ]
