# Generated by Django 5.2.10 on 2026-01-24 16:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_linktype_disabled"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "royalty_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Royalty share percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "unpublished_books",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of book titles not yet published as audiobooks",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "narrations",
                    models.ManyToManyField(
                        blank=True, related_name="agreements", to="books.narration"
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="partners.partner",
                    ),
                ),
            ],
        ),
    ]
