# Generated by Django 5.2.10 on 2026-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_linktype_disabled"),
        ("partners", "0002_agreement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreement",
            name="unpublished_books",
        ),
        migrations.AddField(
            model_name="agreement",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="agreements", to="books.book"
            ),
        ),
    ]
