# Generated by Django 5.2.10 on 2026-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_linktype_disabled"),
        ("partners", "0003_remove_agreement_unpublished_books_agreement_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="agreement_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file of the signed agreement",
                null=True,
                upload_to="agreements/",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="books",
            field=models.ManyToManyField(
                blank=True,
                related_name="agreements",
                to="books.book",
                verbose_name="Books (unpublished)",
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="narrations",
            field=models.ManyToManyField(
                blank=True,
                related_name="agreements",
                to="books.narration",
                verbose_name="Narrations (published books)",
            ),
        ),
    ]
