# Generated by Django 5.2.10 on 2026-01-24 19:34

import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0004_agreement_agreement_file_alter_agreement_books_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="agreement_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file of the signed agreement",
                null=True,
                upload_to=partners.models.agreement_file_path,
            ),
        ),
    ]
