# Generated by Django 5.2.10 on 2026-01-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0005_alter_agreement_agreement_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month_of_sale",
                    models.DateField(
                        help_text="First day of the sale month (e.g., 2025-06-01 for June 2025)"
                    ),
                ),
                (
                    "source_file",
                    models.CharField(
                        help_text="XLSX filename the row was parsed from",
                        max_length=255,
                    ),
                ),
                (
                    "drive_id",
                    models.CharField(
                        help_text="Google Drive file ID of the source XLSX file",
                        max_length=100,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "sales_type",
                    models.CharField(
                        help_text="Channel of sale, e.g. retail, subscription, or pool",
                        max_length=100,
                    ),
                ),
                ("isbn", models.CharField(max_length=50)),
                (
                    "retailer",
                    models.CharField(
                        help_text="Retailer/platform where the audiobook was sold",
                        max_length=255,
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Number of books acquired in this sale"
                    ),
                ),
                ("amount_currency", models.CharField(max_length=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount received from distributor, adjusted for their share (e.g. Google Play takes ~50%)",
                        max_digits=10,
                    ),
                ),
            ],
        ),
    ]
