# Generated by Django 5.2.10 on 2026-01-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0006_salerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salerecord",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
