# Generated by Django 5.2.10 on 2026-01-31 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0025_add_isbn_model"),
        ("partners", "0007_alter_salerecord_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salerecord",
            name="isbn",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale_records",
                to="books.isbn",
            ),
        ),
    ]
