# Generated by Django 5.2.10 on 2026-02-01 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0008_add_isbn_fk_to_salerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="partneruser",
            name="login_uuid",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, null=True, unique=True
            ),
        ),
    ]
