# Generated by Django 5.2.10 on 2026-02-08 21:17

import django.db.models.deletion
import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0009_add_login_uuid_to_partner_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreement",
            name="agreement_file",
            field=models.FileField(
                blank=True,
                help_text="PDF file of the signed agreement",
                null=True,
                upload_to="agreements/",
            ),
        ),
        migrations.CreateModel(
            name="AgreementFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=partners.models.agreement_file_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="partners.agreement",
                    ),
                ),
            ],
        ),
    ]
