# Generated by Django 5.2.10 on 2026-02-08 21:17

from django.db import migrations


def migrate_agreement_files(apps, schema_editor):
    """Move existing agreement_file values to new AgreementFile model."""
    Agreement = apps.get_model("partners", "Agreement")
    AgreementFile = apps.get_model("partners", "AgreementFile")

    for agreement in Agreement.objects.exclude(agreement_file="").exclude(
        agreement_file__isnull=True
    ):
        AgreementFile.objects.create(
            agreement=agreement,
            file=agreement.agreement_file,
        )


def reverse_migration(apps, schema_editor):
    """Move AgreementFile rows back to Agreement.agreement_file."""
    AgreementFile = apps.get_model("partners", "AgreementFile")

    for agreement_file in AgreementFile.objects.all():
        agreement = agreement_file.agreement
        agreement.agreement_file = agreement_file.file
        agreement.save(update_fields=["agreement_file"])


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0010_add_agreement_file_model"),
    ]

    operations = [
        migrations.RunPython(migrate_agreement_files, reverse_migration),
    ]
