# Generated by Django 5.2.10 on 2026-02-08 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0011_migrate_agreement_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agreement",
            name="agreement_file",
        ),
    ]
