import os
import unittest
from datetime import date

from .models import RoyaltyRow
from .parse_findaway_report import parse_findaway_report


class TestParseFindawayReport(unittest.TestCase):
    def test_parse_report(self):
        # Load test file
        test_file = os.path.join(
            os.path.dirname(__file__),
            "Findaway Belaudiobooks (2025-06 Digital Royalty).xlsx",
        )
        with open(test_file, "rb") as f:
            content = f.read()

        filename = "Findaway Belaudiobooks (2025-06 Digital Royalty).xlsx"
        rows = parse_findaway_report(content, filename)

        sale_month = date(2025, 6, 1)

        expected_rows = [
            # Retail (4 rows)
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Палёт над гняздом зязюлі",
                sales_type="Retail",
                royalty_rate=0.5,
                display_number="CD5216806",
                isbn="9798347944019",
                publisher="audiobooks.by",
                partner="Google Play",
                promotion=None,
                sale_territory="PL",
                currency="USD",
                dlp=12,
                price_type="Gross",
                sales_qty=1,
                revenue=12,
                royalty_earned=6,
                less_distribution_fee=1.2,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=4.8,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Пасажыры карабля Тэсея",
                sales_type="Retail",
                royalty_rate=0.5,
                display_number="CD5015951",
                isbn="9798882408120",
                publisher="audiobooks.by",
                partner="Spotify",
                promotion=None,
                sale_territory="US",
                currency="USD",
                dlp=10,
                price_type="Gross",
                sales_qty=1,
                revenue=10,
                royalty_earned=5,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=5,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Па той бок тэлеэкрана",
                sales_type="Retail",
                royalty_rate=0.5,
                display_number="CD5037692",
                isbn="9798882395345",
                publisher="Радыё Свабода",
                partner="Google Play",
                promotion=None,
                sale_territory="RU",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Па што ідзеш, воўча?",
                sales_type="Retail",
                royalty_rate=0.5,
                display_number="CD5247928",
                isbn="9798318257742",
                publisher="Euroradio",
                partner="Google Play",
                promotion=None,
                sale_territory="PL",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            # Subscription (5 rows)
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Адвечным шляхам",
                sales_type="Subscription-Credit Based",
                royalty_rate=0.4,
                display_number="CD4658547",
                isbn="9798368900551",
                publisher="Лятучы ўніверсітэт",
                partner="Audiobooks.com",
                promotion=None,
                sale_territory="DE",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Апошнія сведкі",
                sales_type="Subscription-Credit Based",
                royalty_rate=0.4,
                display_number="CD1247396",
                isbn="9798368936024",
                publisher="Фонд Kamunikat.org",
                partner="Audiobooks.com",
                promotion=None,
                sale_territory="MY",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Малая падарожная кніга па Горадзе СОНца",
                sales_type="Subscription-Credit Based",
                royalty_rate=0.4,
                display_number="CD1318294",
                isbn="9798868756849",
                publisher="audiobooks.by",
                partner="Audiobooks.com",
                promotion=None,
                sale_territory="SE",
                currency="USD",
                dlp=7,
                price_type="Gross",
                sales_qty=1,
                revenue=7,
                royalty_earned=2.8,
                less_distribution_fee=0.56,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=2.24,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Метод Мацкевича",
                sales_type="Subscription-Credit Based",
                royalty_rate=0.4,
                display_number="CD4739262",
                isbn="9798368927299",
                publisher="Лятучы ўніверсітэт",
                partner="Audiobooks.com",
                promotion=None,
                sale_territory="GR",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Мёртвым не баліць",
                sales_type="Subscription-Credit Based",
                royalty_rate=0.4,
                display_number="CD1345342",
                isbn="9798868712531",
                publisher="audiobooks.by",
                partner="Audiobooks.com",
                promotion=None,
                sale_territory="US",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=1,
                revenue=0,
                royalty_earned=0,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0,
            ),
            # Pool (2 rows)
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="PR: как строить коммуникацию в публичном пространстве",
                sales_type="Pool",
                royalty_rate=None,
                display_number="CD4707152",
                isbn="9798368927589",
                publisher="Лятучы ўніверсітэт",
                partner="Spotify",
                promotion=None,
                sale_territory="FR",
                currency="USD",
                dlp=0,
                price_type="Gross",
                sales_qty=0,
                revenue=None,
                royalty_earned=0.04,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0.04,
            ),
            RoyaltyRow(
                sale_month=sale_month,
                source_file=filename,
                title="Апошняя кніга пана А.",
                sales_type="Pool",
                royalty_rate=None,
                display_number="CD3468557",
                isbn="9781669686163",
                publisher="Янушкевіч",
                partner="Spotify",
                promotion=None,
                sale_territory="DE",
                currency="USD",
                dlp=15,
                price_type="Gross",
                sales_qty=0,
                revenue=None,
                royalty_earned=0.2,
                less_distribution_fee=0,
                exchange_rate=None,
                royalty_payable_currency="USD",
                royalty_payable=0.2,
            ),
        ]

        self.assertEqual(len(rows), len(expected_rows))
        for i, (actual, expected) in enumerate(zip(rows, expected_rows)):
            self.assertEqual(actual, expected, f"Row {i} mismatch")


if __name__ == "__main__":
    unittest.main()
