name: continuous-testing-job

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        sudo apt-get install gettext
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python -m unittest -v tests/production_data_json_contract_test.py
