name: data-json-contract

on:
  schedule:
    - cron:  '0 20 * * *'
  workflow_dispatch:

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        cd contract_test
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd contract_test
        pytest test_data_json_contract.py
