name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.READ_REPO_TOKEN }}
        submodules: "true"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cp .env.test .env
    - name: Create migrations
      run: |
        python manage.py makemigrations --settings=booksby.sqlite_settings
    - name: Run Tests
      run: |
        python manage.py test --verbosity=2 --settings=booksby.sqlite_settings
